### PR TITLE
minor improvements in wording and grammar

### PR DESCRIPTION
**Pull request by aleonidex**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Minor changes in a number of English pages:
- improved wording
- improved grammar

Thanks!

### CODE REVIEW

**Comment by yfm-team** [comment]
Все готово!
Commit: 183089da21cf28bdda28afe23aba2f79fc4bb510
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-146434c8-a20f-433d-b8b4-229e6560ff7d/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-146434c8-a20f-433d-b8b4-229e6560ff7d/en/index.html).

**Comment by aleonidex** [comment]
All good!

**Review by vnkiryushkin — APPROVED** [review]

**Comment by yfm-team** [comment]
Возникла ошибка. Пожалуйста, свяжитесь с администратором и укажите идентификатор запроса: 3962b3f4-0583-4d8e-8653-d4869aa6afea

**Comment by vnkiryushkin** [comment]
@aleonidex, hello. Thank you for your interest and attention to the Yandex Cloud documentation. Unfortunately, I cannot accept edits to the English version, because we have a separate internal process for localization. But I will definitely pass [your commit](https://github.com/yandex-cloud/docs/pull/859/commits/183089da21cf28bdda28afe23aba2f79fc4bb510) to the localizers for verification and implementation.

Regarding the edit in the Russian version: yes, indeed, the wording may confuse the user. Accepted. 

Please write here [billing account ID](https://yandex.cloud/en/docs/billing/concepts/billing-account#billing-account-id) in Yandex Cloud so that we can award you a grant as part of the [content program](https://cloud.yandex.ru/content-program).

**Pull request merged**
