### PR TITLE
fix: info about Terraform providers license

### PR DESCRIPTION
**Pull request by kvendingoldo**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Description of changes:
Added info about Terraform lisences

### CODE REVIEW

**Comment by kvendingoldo** [comment]
@SerjKanunnikov may I ask you to check PR, pls?

**Comment by yfm-team** [comment]
Все готово!
Commit: f93c2d895cefc95d40c4af969e091e947dbb4346
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-ef2b4f26-e94f-460d-b2eb-6b4413e63e99/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-ef2b4f26-e94f-460d-b2eb-6b4413e63e99/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: 103f982316f643184abc8992bad2cf03562f016c
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-5987095a-c1c5-41aa-a734-64c15f80624c/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-5987095a-c1c5-41aa-a734-64c15f80624c/en/index.html).

**Comment by kvendingoldo** [comment]
@tatlush can you check it pls?

**Comment by SerjKanunnikov** [comment]
> @SerjKanunnikov may I ask you to check PR, pls?

Hello! Sorry for the late answer, we're looking into your PR. Thank you!

**Comment by yfm-team** [comment]
Все готово!
Commit: 0ee15b954c7821750f6dcd7b34178400b02cd234
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-dc2b1b0b-7361-4db9-ae48-dea29271eae6/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-dc2b1b0b-7361-4db9-ae48-dea29271eae6/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: 29780fb66fb7ce7d26c1274b58be9071a84377d4
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-44775d38-a0cb-49db-9ea7-d7c8ae28028d/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-44775d38-a0cb-49db-9ea7-d7c8ae28028d/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: 8f756204fa2d0cddecd431224fed99fc46f9f772
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-77c5ae7e-7cff-430a-aa56-691d52d7fbd0/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-77c5ae7e-7cff-430a-aa56-691d52d7fbd0/en/index.html).

**Review by vnkiryushkin — APPROVED** [review]

**Comment by vnkiryushkin** [comment]
@kvendingoldo, hello. I'm sorry for the delay. I've been getting approval from lawyers for a long time. Thank you for making our documentation better. I improved PR a little and merged. I also deleted the edits in English. They will be added a little later according to our process.

Please write here [billing account ID](https://yandex.cloud/en/docs/billing/concepts/billing-account#billing-account-id) in Yandex Cloud so that we can award you a grant as part of the [content program](https://cloud.yandex.ru/content-program).

**Pull request merged**
