### PR TITLE
Varlamov move2

### PR DESCRIPTION
**Pull request by var1amov**
Перенос существующей ВМ Linux в другое облако / папку через снятие образа (dd) и объектное хранилище. В помощи не нашёл примеров, но на просторах Интернета они есть.

### CODE REVIEW

**Comment by yfm-team** [comment]
Есть критические ошибки, собрать документацию невозможно. Исправьте их и повторите попытку.

:x:  Link is unreachable: image-create/custom-image.md in /ru/compute/operations/index.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md in /ru/_includes/compute/gpu-os.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md in /ru/_includes/compute/gpu-os.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md in /ru/_includes/compute/gpu-os.md
:x:  Link is unreachable: ../image-create/custom-image.md in /ru/compute/operations/vm-operate/install-nvidia-drivers.md
:x:  Link is unreachable: custom-image.md in /ru/compute/operations/image-create/upload.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md#virtio in /ru/_includes/compute/image-create-requirements.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md#serial-console in /ru/_includes/compute/image-create-requirements.md
:x:  Link is unreachable: ../../resource-manager/concepts/resources-hierarchy.md#cloud in /ru/compute/operations/image-create/move.md
:x:  Link is unreachable: ../../resource-manager/concepts/resources-hierarchy.md#folder in /ru/compute/operations/image-create/move.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md in /ru/_includes/compute/gpu-os.md
:x:  Link is unreachable: ../operations/image-create/custom-image.md in /ru/compute/concepts/filesystem.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md in /ru/marketplace/operations/create-image.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md#virtio in /ru/_includes/compute/image-create-requirements.md
:x:  Link is unreachable: ../../compute/operations/image-create/custom-image.md#serial-console in /ru/_includes/compute/image-create-requirements.md
:x:   No such file or has no access to /ru/compute/operations/image-create/custom-image.md

**Comment by yfm-team** [comment]
Есть предупреждения, их нужно исправить:

:warning: Variable className not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable message not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable urlEncodedRefName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isCurrent not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isFilteringClass not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable refName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isNotDefault not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable urlEncodedRefName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isCurrent not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isFilteringClass not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable refName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isNotDefault not found in /ru/compute/operations/image-create/custom-image.md
:warning: Title not found: image-create/custom-image.md in /ru/compute/operations/index.md
:warning: Variable className not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable message not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable urlEncodedRefName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isCurrent not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isFilteringClass not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable refName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isNotDefault not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable urlEncodedRefName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isCurrent not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable index not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isFilteringClass not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable refName not found in /ru/compute/operations/image-create/custom-image.md
:warning: Variable isNotDefault not found in /ru/compute/operations/image-create/custom-image.md
:warning: Title not found: custom-image.md in /ru/compute/operations/image-create/upload.md
:warning: Title not found: ../../compute/operations/image-create/custom-image.md in /ru/marketplace/operations/create-image.md

**Comment by yfm-team** [comment]
Есть критические ошибки, собрать документацию невозможно. Исправьте их и повторите попытку.

:x:  Link is unreachable: ../../resource-manager/concepts/resources-hierarchy.md#cloud in /ru/compute/operations/image-create/move.md
:x:  Link is unreachable: ../../resource-manager/concepts/resources-hierarchy.md#folder in /ru/compute/operations/image-create/move.md

**Comment by yfm-team** [comment]
Есть критические ошибки, собрать документацию невозможно. Исправьте их и повторите попытку.

:x:  Link is unreachable: ../../resource-manager/concepts/resources-hierarchy.md#cloud in /ru/compute/operations/image-create/move.md
:x:  Link is unreachable: ../../resource-manager/concepts/resources-hierarchy.md#folder in /ru/compute/operations/image-create/move.md

**Review by var1amov — COMMENTED** [review]
Сейчас должно сработать.

**Review by var1amov — COMMENTED** [review]
Возможно, раньше сделал слишком много изменений за раз, поэтому блокировало.

**Review by var1amov — COMMENTED** [review]
Очередная попытка добавить статью про перенос ВМ внутри облака через клонирование диска из ОС

**Comment by var1amov** [comment]
Не понятно, что не так...

**Pull request closed without merging**
