### PR TITLE
Removed from bucket policy information about adding user groups

### PR DESCRIPTION
**Pull request by Algeran**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Description of changes:

According to support ticket UF064009, specifying organisation user groups in bucket policies does not actually grant permissions to users of the corresponding group.

### CODE REVIEW

**Comment by yfm-team** [comment]
Все готово!
Commit: c0bbb8cee26456c1b532f7ae167cee1fb391bb31
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-7dc42bfe-9691-40db-b64c-68ce0e83164e/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-7dc42bfe-9691-40db-b64c-68ce0e83164e/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: 636c10f97a62c8519742e40be75cc8c5e5bbaefe
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-5d27e6f9-a2fe-4798-b26a-b55b0691bfda/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-5d27e6f9-a2fe-4798-b26a-b55b0691bfda/en/index.html).

**Comment by vnkiryushkin** [comment]
@Algeran, hello. Thank you for making our documentation better.

I apologize for the long reaction to your request. I rechecked the functionality with the developers and really identified a bug.
We will remove the mention of the possibility of specifying a User Group in the bucket policy. We will update a documentation through an internal process, the updated documentation will be available in Russian on the evening of 17.12.25. The English version will be available a week later.

Please write here the [billing account ID](https://yandex.cloud/en-ru/docs/billing/concepts/billing-account#billing-account-id) in Yandex Cloud so that we can award you a grant as part of the [content program](https://yandex.cloud/ru/content-program). The request is closed.

**Comment by Algeran** [comment]
@vnkiryushkin , hi. Thanks for the confirmation, I was glad to help.
Here is our billing account ID - `dn2ea7dv5t0ikhh8rlrq`.

**Comment by vnkiryushkin** [comment]
@Algeran The grant has been issued.

**Pull request closed without merging**
