### PR TITLE
Update loki.md

### PR DESCRIPTION
**Pull request by kuPyxa**
Change Loki gateway name

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Description of changes:

In reality Loki gateway name is different

https://server-yfm.website.yandexcloud.net/server-yfm-ef16797e-49c7-400d-a15f-b0c32b6b02a6/ru/managed-kubernetes/operations/applications/loki.html

### CODE REVIEW

**Comment by yfm-team** [comment]
Все готово!
Commit: b7bd3b9d51f69fb7dbdd4a0cd77a6190d5160098
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-8494689d-3165-4b7a-9a38-9b61a458688d/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-8494689d-3165-4b7a-9a38-9b61a458688d/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: 0f9155f19323d3f88fb4f932244788fd08d218fd
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-6347e6bc-b961-4b82-a058-e384c5f1a172/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-6347e6bc-b961-4b82-a058-e384c5f1a172/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: 72a2582b065d9cc164dcacb49c4499bd897d02e3
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-ef16797e-49c7-400d-a15f-b0c32b6b02a6/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-ef16797e-49c7-400d-a15f-b0c32b6b02a6/en/index.html).

**Review by vnkiryushkin — APPROVED** [review]

**Comment by vnkiryushkin** [comment]
@kuPyxa, hello. Thank you for making our documentation better. The name of the Loki gateway service has indeed changed. I edited the PR, offered a more universal instruction, in case the developer changes the name of the service again.

I also corrected the instructions for helm chart in accordance with the new version in the Marketplace.

Please write here [billing account ID](https://yandex.cloud/en-ru/docs/billing/concepts/billing-account#billing-account-id) in Yandex Cloud so that we can award you a grant as part of the [content program](https://cloud.yandex.ru/content-program).

**Comment by kuPyxa** [comment]
Hello. My billing account id is dn2t3j8b2nvea7hflttf. Thank you!

**Comment by vnkiryushkin** [comment]
@kuPyxa The grant has been issued.

**Pull request merged**
