### PR TITLE
Update intro.md

### PR DESCRIPTION
**Pull request by Pankraty**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Description of changes:
Extend the list of supported platforms, according to the documentation

See https://cloud.yandex.ru/docs/ydb/reference/ydb-sdk/
image

### CODE REVIEW

**Comment by yfm-team** [comment]
Все готово! 
Проверьте результат: [RU](https://storage.yandexcloud.net/server-yfm/server-yfm-2dd8a4d0-cb8e-11ec-8bdc-fe28384d3f87/ru/index.html),
Check the result: [EN](https://storage.yandexcloud.net/server-yfm/server-yfm-2dd8a4d0-cb8e-11ec-8bdc-fe28384d3f87/en/index.html).

**Comment by alexv-smirnov** [comment]
Hi. Thank you for the fix!
This doc source has moved to https://github.com/ydb-platform/ydb/blob/main/ydb/docs/ru/core/reference/ydb-sdk. I would appreciate if you make another PR against the new location, including both RU and EN source changes. We'll be happy to merge it with your authorship then.

**Comment by Pankraty** [comment]
Sorry, I was not quite specific about the page address. The page fixed by this PR is located here: https://cloud.yandex.ru/docs/ydb/concepts/, and it states:

> To interact with YDB, you can use the [YDB CLI](https://cloud.yandex.com/en/docs/ydb/reference/ydb-cli/) or [SDK](https://cloud.yandex.com/en/docs/ydb/reference/ydb-sdk/) for Java, Python, Node.js, PHP, and Go.

I've added C# to the list.

As for this link (https://cloud.yandex.ru/docs/ydb/reference/ydb-sdk/) - I used it as a reference to what languages are actually supported.

Could you please reopen the PR? I've added changes in both languages.

**Comment by Pankraty** [comment]
I just press Edit on Github on the page and get redirected to this repo, this exact page I changed. Does this mean, the link on the page is also wrong? 
Screenshot_2022-05-18-19-36-18-193_org mozilla firefox

**Pull request closed without merging**
