### PR TITLE
Fixed default values replica.fetch.max.bytes and max.message.bytes

### PR DESCRIPTION
**Pull request by FactorT**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Description of changes:
Current default values of replica.fetch.max.bytes and max.message.bytes don't satisfy for description of both params:
replica.fetch.max.bytes >= message.max.bytes + 12
message.max.bytes <= replica.fetch.max.bytes - 12

### CODE REVIEW

**Comment by yfm-team** [comment]
Все готово!
Commit: ec57a9b2c52389ee146c8d30e49a59e205afb211
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-5b1bf6ad-67a4-4087-8e0b-350f04f87e9d/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-5b1bf6ad-67a4-4087-8e0b-350f04f87e9d/en/index.html).

**Comment by redalka-cloud** [comment]
Hi @FactorT , 
Thank you for reporting the issue.
In fact, the default parameter values are valid and reflect the ones in the Kafka Apache documentation:

https://kafka.apache.org/documentation/#brokerconfigs_message.max.bytes
https://kafka.apache.org/documentation/#brokerconfigs_replica.fetch.max.bytes

We'll rework the confusing statements in their descriptions.
I'm closing this PR, but I'd like to reward you for the help. Please provide you billing account ID in Yandex Cloud, so we can issue a grant as part of the [content program](https://yandex.cloud/ru/content-program).

**Comment by FactorT** [comment]
@redalka-cloud ajejaa85j7lmuo9r8nvc

**Comment by redalka-cloud** [comment]
@FactorT Please provide a 20-character ID that is available on your Billing Account page:
image

**Comment by FactorT** [comment]
@redalka-cloud dn2rien5e0o3svqb5rcj

**Comment by redalka-cloud** [comment]
> @redalka-cloud dn2rien5e0o3svqb5rcj

Thank you! Grant has been requested.

**Pull request closed without merging**
