### PR TITLE
Changed the method of setting roles to a more secure one

### PR DESCRIPTION
**Pull request by dahnlka**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

Description of changes:
Changed the method of setting permissions in Terraform examples to a safer one.
Preferent use https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/resourcemanager_folder_iam_member

It is more correct to use this method instead of the current ones. Because when you destroy, all attached roles on the service accounts in the cloud are deleted. What are more destructive consequences for beginners

### CODE REVIEW

**Comment by yfm-team** [comment]
Все готово!
Commit: ba1af28a419fcaccb3d62c3470345d9602f2ea8e
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-93f2b878-e02d-441d-992f-910bdcb5d0be/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-93f2b878-e02d-441d-992f-910bdcb5d0be/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: de4d550551bf89b89b3b14d69e4132c5e9761cfd
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-340d6841-0939-4f33-aa23-51ab6231a786/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-340d6841-0939-4f33-aa23-51ab6231a786/en/index.html).

**Comment by yfm-team** [comment]
Все готово!
Commit: 1744d5315bbca1742dcfb086345a205f349ebfe8
Проверьте результат: [RU](https://server-yfm.website.yandexcloud.net/server-yfm-d476bc33-b5f3-4350-8528-5b81c1bb5f75/ru/index.html).
Check the result: [EN](https://server-yfm.website.yandexcloud.net/server-yfm-d476bc33-b5f3-4350-8528-5b81c1bb5f75/en/index.html).

**Comment by iglunchadze** [comment]
Hi @dahnlka, and thank you for your edits! We ran them by our developers, and they confirmed that using `yandex_resourcemanager_folder_iam_member` is indeed preferable.

You are entitled to a grant according to our [content program](https://cloud.yandex.ru/content-program) (Russian). Could you please provide the ID of your Yandex Cloud [billing account](https://console.cloud.yandex.com/billing)?

**Comment by dahnlka** [comment]
@iglunchadze Thank you, billing id: dn2v1o10vvfghc2ddr69

**Comment by iglunchadze** [comment]
We have given out the grant!

**Pull request merged**
